rence/pom.xml, rence/src/main/java/test/com/rence/backoffice/BackOfficeController.java, rence/src/main/java/test/com/rence/backoffice/BackOfficeDAO.java, rence/src/main/java/test/com/rence/backoffice/BackOfficeDAOImpl.java, rence/src/main/java/test/com/rence/backoffice/BackOfficeService.java, rence/src/main/java/test/com/rence/backoffice/BackOfficeVO.java, rence/src/main/resources/jdbc/oracle.properties, rence/src/main/resources/jdbc/sqlMapper_backoffice.xml, rence/src/main/resources/jdbc/sqlMapper_office.xml, rence/src/main/resources/jdbc/sqlMapper_user.xml, rence/src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml, rence/src/main/webapp/WEB-INF/spring/root-context.xml, rence/src/main/webapp/WEB-INF/web.xml
=> [feat] 기본적인 maven 삽입, bean 등록

rence/src/main/java/test/com/user/UserController.java, rence/src/main/java/test/com/user/UserDAO.java, rence/src/main/java/test/com/user/UserDAOimpl.java, rence/src/main/java/test/com/user/UserSerivice.java, rence/src/main/java/test/com/user/UserVO.java
User VO,DAO,DAOimpl,Controller 등록
=> [feat]User VO,DAO,DAOimpl,Controller 등록

rence/pom.xml, rence/src/main/java/test/com/rence/backoffice/BackOfficeController.java, rence/src/main/java/test/com/rence/backoffice/BackOfficeDAO.java, rence/src/main/java/test/com/rence/backoffice/BackOfficeDAOImpl.java, rence/src/main/java/test/com/rence/backoffice/BackOfficeOperationgTimeVO.java, rence/src/main/java/test/com/rence/backoffice/BackOfficeService.java, rence/src/main/java/test/com/rence/backoffice/BackOfficeVO.java, rence/src/main/java/test/com/rence/backoffice/OperatingTime.java, rence/src/main/java/test/com/rence/sendemail/AuthSendEmail.java, rence/src/main/java/test/com/rence/sendemail/AuthVO.java, rence/src/main/resources/jdbc/sqlMapper_backoffice.xml, rence/src/main/webapp/WEB-INF/spring/root-context.xml
=> [feat] BackOffice 신청, RseponseBody maven 추가

rence/src/main/java/test/com/user/UserController.java, rence/src/main/java/test/com/user/UserDAO.java, rence/src/main/java/test/com/user/UserDAOimpl.java, rence/src/main/java/test/com/user/UserFAO.java, rence/src/main/java/test/com/user/UserFAOimpl.java, rence/src/main/java/test/com/user/UserFileuploadService.java, rence/src/main/java/test/com/user/UserSerivice.java, rence/src/main/java/test/com/user/UserSignupController.java, rence/src/main/java/test/com/user/UserVO.java, rence/src/main/java/test/com/user/idCheck.js, rence/src/main/resources/jdbc/sqlMapper_office.xml, rence/src/main/resources/jdbc/sqlMapper_user.xml
=> [feat] FAO추가 및 USER수정

rence/src/main/java/test/com/rence/backoffice/BackOfficeController.java
=> [feat] BackOffice controller 수정

rence/src/main/java/test/com/rence/backoffice/BackOfficeController.java, rence/src/main/java/test/com/rence/backoffice/BackOfficeDAO.java, rence/src/main/java/test/com/rence/backoffice/BackOfficeDAOImpl.java, rence/src/main/java/test/com/rence/backoffice/BackOfficeLogin.java, rence/src/main/java/test/com/rence/backoffice/BackOfficeService.java, rence/src/main/java/test/com/rence/sendemail/AuthSendEmail.java, rence/src/main/java/test/com/rence/sendemail/EmailVO.java, rence/src/main/resources/jdbc/sqlMapper_backoffice.xml, rence/src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml, rence/src/main/webapp/WEB-INF/spring/root-context.xml
=> [feat] BackOffice Login , Logout

rence/src/main/java/test/com/rence/user/HeaderController.java
=> [feat]add HeaderController

rence/src/main/java/test/com/rence/backoffice/BackOfficeController.java, rence/src/main/java/test/com/rence/backoffice/BackOfficeDAO.java, rence/src/main/java/test/com/rence/backoffice/BackOfficeDAOImpl.java, rence/src/main/java/test/com/rence/backoffice/BackOfficeService.java, rence/src/main/java/test/com/rence/sendemail/AuthSendEmail.java, rence/src/main/resources/jdbc/sqlMapper_backoffice.xml, rence/src/main/webapp/WEB-INF/spring/root-context.xml
=> [feat] BackOffice pw 찾기 진행 중

rence/src/main/java/test/com/rence/user/UserController.java, rence/src/main/java/test/com/rence/user/UserDAO.java, rence/src/main/java/test/com/rence/user/UserDAOimpl.java, rence/src/main/java/test/com/rence/user/UserLoginInterceptor.java, rence/src/main/java/test/com/rence/user/UserSerivice.java, rence/src/main/resources/jdbc/sqlMapper_user.xml, rence/src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
- User Login기능 구현
- User Logout기능 구현
-  UserLoginInterceptor 추가
=> [feat] add User login,logout

rence/src/main/java/test/com/rence/user/UserController.java
=> [feat]  Edit UserController-LoginOk

rence/pom.xml, rence/src/main/java/test/com/rence/user/UserController.java
- UserController loginOK  반환값 JSONObject 수정
-  JSONObject 사용을 위한 라이브러리 추가
=> [feat] Edit UserController loginOK and pom.xml

rence/src/main/java/test/com/rence/backoffice/BackOfficeController.java, rence/src/main/java/test/com/rence/backoffice/BackOfficeDAO.java, rence/src/main/java/test/com/rence/backoffice/BackOfficeDAOImpl.java, rence/src/main/java/test/com/rence/backoffice/BackOfficeService.java, rence/src/main/java/test/com/rence/sendemail/AuthVO.java, rence/src/main/java/test/com/rence/sendemail/BackOfficeSendEmail.java, rence/src/main/resources/jdbc/sqlMapper_backoffice.xml, rence/src/main/webapp/WEB-INF/spring/root-context.xml
=> [feat] BackOffice Email

rence/src/main/java/test/com/rence/user/UserController.java, rence/src/main/java/test/com/rence/user/UserDAO.java, rence/src/main/java/test/com/rence/user/UserDAOimpl.java, rence/src/main/java/test/com/rence/user/UserSignupController.java, rence/src/main/java/test/com/rence/user/UserVO.java
UserController,userSignupController 등 수정파일 업로드
=> [feat] UserController,userSignupController 등 수정파일 업로드

rence/src/main/java/test/com/rence/user/UserController.java
=> [feat] edit UserController

rence/src/main/java/test/com/rence/sendemail/UserSendEmail.java, rence/src/main/java/test/com/rence/user/UserController.java
=> [feat] User 아이디 찾기

rence/pom.xml, rence/src/main/java/test/com/rence/backoffice/BackOfficeController.java, rence/src/main/java/test/com/rence/sendemail/AES256Util.java, rence/src/main/java/test/com/rence/sendemail/BackOfficeSendEmail.java
=> [feat] BackOffice 이메일 링크 암호화

rence/src/main/java/test/com/rence/user/UserController.java, rence/src/main/java/test/com/rence/user/UserDAOimpl.java, rence/src/main/java/test/com/rence/user/UserSerivice.java, rence/src/main/resources/jdbc/sqlMapper_user.xml
=> [feat] User user_pw_updte

rence/src/main/java/test/com/rence/backoffice/BackOfficeController.java, rence/src/main/java/test/com/rence/backoffice/BackOfficeDAO.java, rence/src/main/java/test/com/rence/backoffice/BackOfficeDAOImpl.java, rence/src/main/java/test/com/rence/backoffice/BackOfficeLogin.java, rence/src/main/java/test/com/rence/backoffice/BackOfficeService.java, rence/src/main/resources/jdbc/sqlMapper_backoffice.xml
=> [feat] BackOffice Seeting page

rence/src/main/java/test/com/rence/sendemail/UserSendEmail.java, rence/src/main/java/test/com/rence/user/UserController.java, rence/src/main/java/test/com/rence/user/UserDAO.java, rence/src/main/java/test/com/rence/user/UserDAOimpl.java, rence/src/main/java/test/com/rence/user/UserSerivice.java, rence/src/main/resources/jdbc/sqlMapper_user.xml
- User 아이디 찾기 코드 수정
- user 비밀번호 찾기 코드 구현
- User 비밀번호 수정 코드 수정
- User vo,dao,impl,service수정
- User 쿼리문 수정
=> [feat] User 아이디찾기,비밀번호찾기,비밀번호수정

rence/src/main/java/test/com/rence/user/UserController.java
=> [refactor] 이미지수정 서블릿방식 수정

rence/src/main/java/test/com/rence/user/UserDAO.java, rence/src/main/java/test/com/rence/user/UserDAOimpl.java, rence/src/main/java/test/com/rence/user/UserFileuploadService.java, rence/src/main/java/test/com/rence/user/UserJoinController.java, rence/src/main/java/test/com/rence/user/UserSerivice.java, rence/src/main/resources/jdbc/sqlMapper_user.xml
=> [feat] user 이미지수정 및 기타기능

rence/pom.xml
=> [error] spring jdbc수정

rence/src/main/java/test/com/rence/backoffice/BackOfficeController.java, rence/src/main/java/test/com/rence/backoffice/BackOfficeDAO.java, rence/src/main/java/test/com/rence/backoffice/BackOfficeDAOImpl.java, rence/src/main/java/test/com/rence/backoffice/BackOfficeService.java, rence/src/main/java/test/com/rence/backoffice/BackOfficeVO.java, rence/src/main/java/test/com/rence/sendemail/AuthVO.java, rence/src/main/java/test/com/rence/sendemail/BackOfficeSendEmail.java, rence/src/main/resources/jdbc/sqlMapper_backoffice.xml
=> [feat] BackOffice 수정

rence/resources/test/com/rence/UserControllerTest.java, rence/src/main/java/test/com/rence/user/HeaderController.java, rence/src/main/java/test/com/rence/user/MypageController.java, rence/src/main/java/test/com/rence/user/UserController.java, rence/src/main/java/test/com/rence/user/UserDAO.java, rence/src/main/java/test/com/rence/user/UserDAOimpl.java, rence/src/main/java/test/com/rence/user/UserMileage.java, rence/src/main/java/test/com/rence/user/UserMypageVO.java, rence/src/main/java/test/com/rence/user/UserSerivice.java, rence/src/main/resources/jdbc/sqlMapper_user.xml, rence/src/test/java/test/com/rence/UserControllerTest.java
=> [feat] User 컨트롤러 등 작업

rence/src/main/java/test/com/rence/user/HeaderController.java
=> [refactor] 헤더컨트롤러 주석

rence/src/main/java/test/com/rence/sendemail/UserSendEmail.java, rence/src/main/java/test/com/rence/user/UserDAO.java, rence/src/main/java/test/com/rence/user/UserDAOimpl.java, rence/src/main/java/test/com/rence/user/UserJoinController.java, rence/src/main/java/test/com/rence/user/UserSerivice.java, rence/src/main/resources/jdbc/sqlMapper_user.xml
=> [feat]이메일 인증

rence/src/main/java/test/com/rence/user/UserJoinController.java
[refactor] userjoiinController 서블릿방시 변경
=> [refactor] userjoiinController 서블릿방시 변경

rence/src/main/resources/jdbc/sqlMapper_user.xml
=> [refactor] user 쿼리문 변경

rence/src/main/java/test/com/rence/sendemail/UserSendEmail.java, rence/src/main/java/test/com/rence/user/UserDAOimpl.java, rence/src/main/java/test/com/rence/user/UserJoinController.java, rence/src/main/resources/jdbc/sqlMapper_user.xml
=> [refactor]이메일 인증 및 중복체크

rence/src/main/resources/jdbc/oracle.properties, rence/src/main/webapp/WEB-INF/layouts/host_header.jsp, rence/src/main/webapp/WEB-INF/layouts/layout_tiles_landing.jsp, rence/src/main/webapp/WEB-INF/spring/root-context-tiles.xml, rence/src/main/webapp/WEB-INF/tiles_landing.xml, rence/src/main/webapp/WEB-INF/views/backoffice/landing/landing.jsp, rence/src/main/webapp/resources/CSS/host-header.css, rence/src/main/webapp/resources/CSS/host-landing.css, rence/src/main/webapp/resources/CSS/host-login.css, rence/src/main/webapp/resources/JS/header.js, rence/src/main/webapp/resources/JS/host_header.js, rence/src/main/webapp/resources/JS/host_popup.js
- 백오피스 랜딩 페이지 구현
- 기본적인 팝업 JS 구현 (팝업 닫기 등)
=> [feat] 백오피스 랜딩 페이지 구현

rence/src/main/java/test/com/rence/backoffice/BackOfficeController.java, rence/src/main/java/test/com/rence/backoffice/BackOfficeDAO.java, rence/src/main/java/test/com/rence/backoffice/BackOfficeDAOImpl.java, rence/src/main/java/test/com/rence/backoffice/BackOfficeOperationgTimeVO.java, rence/src/main/java/test/com/rence/backoffice/BackOfficeService.java, rence/src/main/java/test/com/rence/backoffice/OperatingTime.java, rence/src/main/java/test/com/rence/master/MasterController.java, rence/src/main/resources/jdbc/sqlMapper_backoffice.xml
=> [feat] BackOfficeOperating VO 수정

rence/src/main/java/test/com/rence/backoffice/BackOfficeDAO.java, rence/src/main/java/test/com/rence/backoffice/BackOfficeDAOImpl.java, rence/src/main/java/test/com/rence/backoffice/BackOfficeLogin.java, rence/src/main/java/test/com/rence/backoffice/BackOfficeOperationgTimeVO.java, rence/src/main/java/test/com/rence/backoffice/BackOfficeService.java, rence/src/main/java/test/com/rence/backoffice/BackOfficeVO.java, rence/src/main/java/test/com/rence/backoffice/OperatingTime.java, rence/src/main/java/test/com/rence/master/MasterController.java, rence/src/main/java/test/com/rence/master/MasterDAO.java, rence/src/main/java/test/com/rence/master/MasterDAOImpl.java, rence/src/main/java/test/com/rence/master/MasterLogin.java, rence/src/main/java/test/com/rence/master/MasterService.java, rence/src/main/java/test/com/rence/master/MasterVO.java, rence/src/main/java/test/com/rence/sendemail/AES256Util.java, rence/src/main/java/test/com/rence/sendemail/BackOfficeSendEmail.java, rence/src/main/java/test/com/rence/sendemail/MasterSendEmail.java, rence/src/main/resources/jdbc/sqlMapper_master.xml, rence/src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml, rence/src/main/webapp/WEB-INF/spring/root-context.xml
=> [feat] Master setting

rence/src/main/java/test/com/rence/user/HeaderController.java, rence/src/main/java/test/com/rence/user/UserDAOimpl.java, rence/src/main/java/test/com/rence/user/UserJoinController.java, rence/src/main/java/test/com/rence/user/UserLoginInterceptor.java, rence/src/main/java/test/com/rence/user/UserMypageVO.java, rence/src/main/java/test/com/rence/user/UserVO.java, rence/src/main/resources/jdbc/sqlMapper_user.xml
=> [refactor]회원가입 수정

rence/src/main/resources/jdbc/oracle.properties
=> [refactor]  데이터베이스 경로 세팅 및 주석처리

rence/src/main/java/test/com/rence/user/MypageController.java, rence/src/main/webapp/resources/CSS/common.css
[feat] 회원 탈퇴 후 세션 끊는 기능 추가하여 수정
=> [feat] 회원 탈퇴 수정

rence/src/main/java/test/com/rence/user/UserDAOimpl.java, rence/src/main/java/test/com/rence/user/UserJoinController.java, rence/src/main/java/test/com/rence/user/UserVO.java, rence/src/main/resources/jdbc/sqlMapper_user.xml
=> [refactor]User 회원가입 구현완료

rence/pom.xml, rence/src/main/java/test/com/rence/backoffice/BackOfficeController.java, rence/src/main/java/test/com/rence/backoffice/BackOfficeDAO.java, rence/src/main/java/test/com/rence/backoffice/BackOfficeDAOImpl.java, rence/src/main/java/test/com/rence/backoffice/BackOfficeService.java, rence/src/main/java/test/com/rence/backoffice/BackOfficeVO.java, rence/src/main/java/test/com/rence/backoffice/OperatingTime.java, rence/src/main/java/test/com/rence/master/MasterController.java, rence/src/main/java/test/com/rence/sendemail/BackOfficeSendEmail.java, rence/src/main/java/test/com/rence/sendemail/MasterSendEmail.java, rence/src/main/resources/jdbc/oracle.properties, rence/src/main/resources/jdbc/sqlMapper_backoffice.xml, rence/src/main/webapp/WEB-INF/views/backoffice/landing/insert.jsp
로그인 조건 추가, 탈퇴 신청 조건 추가, 이메일 인증 후 컬럼 삭제, BackOfficeVO에서 auth_no 삭제
=> [feat] BackOffice 신청 수정 중

rence/src/main/java/test/com/rence/sendemail/UserSendEmail.java, rence/src/main/java/test/com/rence/user/SHA256.java, rence/src/main/java/test/com/rence/user/UserController.java, rence/src/main/java/test/com/rence/user/UserDAOimpl.java, rence/src/main/resources/jdbc/sqlMapper_user.xml
- User 아이디찾기, 비밀번호 찾기, 비밀번호 수정 완료
-  SHA256 암호화 class추가
=> [refactor]User 아이디찾기, 비밀번호 찾기, 비밀번호 수정 완료

rence/src/main/resources/jdbc/sqlMapper_user.xml
- 마일리지 변경에 따른 마이페이지 총 마일리지 금액변경까지 확인함
=> [refactor] 마이페이지 관련 매퍼수정

rence/src/main/java/test/com/rence/common/CustomDateFormatter.java
- String 타입의 HH:mm 형식 시간을 Date로 바꿔주는 함수 추가
=> [feat] CustomDateFormatter 추가

rence/src/main/java/test/com/rence/backoffice/BackOfficeController.java, rence/src/main/java/test/com/rence/backoffice/BackOfficeDAO.java, rence/src/main/java/test/com/rence/backoffice/BackOfficeDAOImpl.java, rence/src/main/java/test/com/rence/backoffice/BackOfficeFAO.java, rence/src/main/java/test/com/rence/backoffice/BackOfficeFAOImpl.java, rence/src/main/java/test/com/rence/backoffice/BackOfficeFileService.java, rence/src/main/java/test/com/rence/backoffice/BackOfficeOperationgTimeVO_datetype.java, rence/src/main/java/test/com/rence/backoffice/BackOfficeService.java, rence/src/main/java/test/com/rence/backoffice/BackOfficeVO.java, rence/src/main/java/test/com/rence/backoffice/OperatingTime.java, rence/src/main/resources/jdbc/sqlMapper_backoffice.xml
이메일 전송 후, 맨 마지막 정보 불러오기, 운영시간 vo 두개로 분기, 파일 업로드 FAO로 별도 작성
=> [feat] BackOffice FAO, 운영시간 수정

rence/src/main/webapp/WEB-INF/views/backoffice/landing/insert.jsp
=> [refactor] 호스트 신청 버그 수정

rence/src/main/java/test/com/rence/backoffice/BackOfficeController.java, rence/src/main/java/test/com/rence/backoffice/BackOfficeDAO.java, rence/src/main/java/test/com/rence/backoffice/BackOfficeDAOImpl.java, rence/src/main/java/test/com/rence/backoffice/BackOfficeFAOImpl.java, rence/src/main/java/test/com/rence/backoffice/BackOfficeOperatingTimeVO.java, rence/src/main/java/test/com/rence/backoffice/BackOfficeOperatingTimeVO_datetype.java, rence/src/main/java/test/com/rence/backoffice/BackOfficeService.java, rence/src/main/java/test/com/rence/backoffice/OperatingTime.java, rence/src/main/resources/jdbc/sqlMapper_backoffice.xml
=> [feat] BackOffice 운영시간 버그 수정

rence/src/main/java/test/com/rence/backoffice/BackOfficeController.java, rence/src/main/java/test/com/rence/backoffice/BackOfficeDAO.java, rence/src/main/java/test/com/rence/backoffice/BackOfficeDAOImpl.java, rence/src/main/java/test/com/rence/backoffice/BackOfficeService.java, rence/src/main/resources/jdbc/sqlMapper_backoffice.xml, rence/src/main/webapp/WEB-INF/views/backoffice/landing/insert.jsp
=> [feat] BackOffice 신청 구현 완료

rence/src/main/java/test/com/rence/backoffice/BackOfficeController.java, rence/src/main/java/test/com/rence/backoffice/BackOfficeVO.java, rence/src/main/java/test/com/rence/master/MasterController.java, rence/src/main/java/test/com/rence/master/MasterDAO.java, rence/src/main/java/test/com/rence/master/MasterDAOImpl.java, rence/src/main/java/test/com/rence/master/MasterService.java, rence/src/main/java/test/com/rence/sendemail/MasterSendEmail.java, rence/src/main/resources/jdbc/sqlMapper_backoffice.xml, rence/src/main/resources/jdbc/sqlMapper_master.xml
master 구현 완료, backoffice 휴무 시, 운영시간 null 처리
=> [feat] Master 구현 완료

rence/src/main/java/test/com/rence/backoffice/OperatingTime.java, rence/src/main/resources/jdbc/sqlMapper_backoffice.xml
=> [feat] BackOffice 운영시간 null 수정

rence/src/main/java/test/com/rence/user/controller/MypageController.java, rence/src/main/java/test/com/rence/user/model/UserDAOimpl.java, rence/src/main/resources/jdbc/sqlMapper_user.xml
=> [refactor] 마일리지 페이지 조건리스트 수정

rence/src/main/java/test/com/rence/dashboard/DashBoardController.java, rence/src/main/java/test/com/rence/dashboard/model/CommentSummaryVO.java, rence/src/main/java/test/com/rence/dashboard/model/CommentVO.java, rence/src/main/java/test/com/rence/dashboard/model/DashBoardDAO.java, rence/src/main/java/test/com/rence/dashboard/model/DashBoardDAOImpl.java, rence/src/main/java/test/com/rence/dashboard/model/PaymentVO.java, rence/src/main/java/test/com/rence/dashboard/model/ReserveSummaryVO.java, rence/src/main/java/test/com/rence/dashboard/model/RoomSummaryVO.java, rence/src/main/java/test/com/rence/dashboard/model/SalesSettlementSummaryVO.java, rence/src/main/java/test/com/rence/dashboard/service/DashBoardService.java, rence/src/main/resources/jdbc/sqlMapper_dashboard.xml, rence/src/main/webapp/WEB-INF/spring/root-context.xml
=> [feat] DashBoard 메인, 예약 관리 구현

rence/src/main/java/test/com/rence/backoffice/BackOfficeDAOImpl.java, rence/src/main/java/test/com/rence/dashboard/model/DashBoardDAOImpl.java
=> [feat] 암호화 부분 삭제

rence/src/main/java/test/com/rence/dashboard/DashBoardController.java, rence/src/main/java/test/com/rence/dashboard/model/DashBoardDAO.java, rence/src/main/java/test/com/rence/dashboard/model/DashBoardDAOImpl.java, rence/src/main/java/test/com/rence/dashboard/model/ReserveVO.java, rence/src/main/java/test/com/rence/dashboard/model/SalesSettlementPreVO.java, rence/src/main/java/test/com/rence/dashboard/model/SalesSettlementVO.java, rence/src/main/java/test/com/rence/dashboard/service/DashBoardService.java, rence/src/main/resources/jdbc/sqlMapper_dashboard.xml
=> [feat] 공간 추가 진행 중

rence/src/main/java/test/com/rence/dashboard/DashBoardController.java, rence/src/main/java/test/com/rence/dashboard/model/DashBoardDAO.java, rence/src/main/java/test/com/rence/dashboard/model/DashBoardDAOImpl.java, rence/src/main/java/test/com/rence/dashboard/service/DashBoardService.java, rence/src/main/java/test/com/rence/master/MasterController.java, rence/src/main/resources/jdbc/sqlMapper_dashboard.xml, rence/src/main/webapp/WEB-INF/layouts/host_header.jsp
=> [feat] host id session 수정

rence/src/main/java/test/com/rence/dashboard/DashBoardController.java, rence/src/main/java/test/com/rence/dashboard/model/DashBoardDAO.java, rence/src/main/java/test/com/rence/dashboard/model/DashBoardDAOImpl.java, rence/src/main/java/test/com/rence/dashboard/service/DashBoardService.java, rence/src/main/resources/jdbc/sqlMapper_dashboard.xml
=> [feat] mapper 오타 수정

rence/src/main/java/test/com/rence/dashboard/DashBoardController.java, rence/src/main/java/test/com/rence/dashboard/model/DashBoardDAO.java, rence/src/main/java/test/com/rence/dashboard/model/DashBoardDAOImpl.java, rence/src/main/java/test/com/rence/dashboard/service/DashBoardService.java, rence/src/main/resources/jdbc/sqlMapper_dashboard.xml
=> [feat] 공간 삭제 진헹 중

rence/src/main/java/test/com/rence/backoffice/BackOfficeLogin.java, rence/src/main/java/test/com/rence/master/MasterLogin.java, rence/src/main/webapp/WEB-INF/layouts/host_header.jsp, rence/src/main/webapp/WEB-INF/layouts/master_header.jsp
=> [feat] master, host 로그인 주석 해제

rence/src/main/java/test/com/rence/user/controller/MypageController.java
회원탈퇴시 로그아웃과 동일하게 쿠기값을 사라져야 하나 쿠키가 남아있는 오류 발견.
회원탈퇴쪽에 코드 추가
=> [refactor] 회원탈퇴시 쿠키가 남아있는 오류  수정

rence/src/main/java/test/com/rence/backoffice/BackOfficeController.java, rence/src/main/java/test/com/rence/dashboard/DashBoardController.java, rence/src/main/java/test/com/rence/dashboard/model/DashBoardDAO.java, rence/src/main/java/test/com/rence/dashboard/model/DashBoardDAOImpl.java, rence/src/main/java/test/com/rence/dashboard/model/ReviewVO.java, rence/src/main/java/test/com/rence/dashboard/service/DashBoardService.java, rence/src/main/java/test/com/rence/master/MasterController.java, rence/src/main/resources/jdbc/sqlMapper_dashboard.xml
backoffice-master 로그인 수정, 공간 등록/수정/삭제
=> [feat] backoffice-master 로그인 수정, 공간 등록/수정/삭제

rence/src/main/java/test/com/rence/dashboard/DashBoardController.java, rence/src/main/java/test/com/rence/dashboard/model/CommentVO.java, rence/src/main/java/test/com/rence/dashboard/model/DashBoardDAO.java, rence/src/main/java/test/com/rence/dashboard/model/DashBoardDAOImpl.java, rence/src/main/java/test/com/rence/dashboard/model/ReserveSummaryVO.java, rence/src/main/java/test/com/rence/dashboard/service/DashBoardService.java, rence/src/main/resources/jdbc/sqlMapper_dashboard.xml
=> [feat] dashboard main 쿼리 수정

rence/src/main/java/test/com/rence/dashboard/model/DashBoardDAOImpl.java, rence/src/main/java/test/com/rence/dashboard/model/ReserveSummaryVO.java, rence/src/main/resources/jdbc/sqlMapper_dashboard.xml
=> [feat] DashBoard 메인 날짜 형식 수정

rence/src/main/java/test/com/rence/dashboard/DashBoardController.java, rence/src/main/java/test/com/rence/dashboard/model/CommentSummaryVO.java, rence/src/main/java/test/com/rence/dashboard/model/CommentVO.java, rence/src/main/java/test/com/rence/dashboard/model/DashBoardDAO.java, rence/src/main/java/test/com/rence/dashboard/model/DashBoardDAOImpl.java, rence/src/main/java/test/com/rence/dashboard/model/ReserveVO.java, rence/src/main/java/test/com/rence/dashboard/model/ReviewVO.java, rence/src/main/java/test/com/rence/dashboard/service/DashBoardService.java, rence/src/main/resources/jdbc/sqlMapper_dashboard.xml
=> [feat] DashBoard mapper id 수정

rence/src/main/java/test/com/rence/backoffice/BackOfficeController.java, rence/src/main/java/test/com/rence/backoffice/BackOfficeSelectVO.java, rence/src/main/java/test/com/rence/dashboard/DashBoardController.java, rence/src/main/java/test/com/rence/dashboard/model/DashBoardDAO.java, rence/src/main/java/test/com/rence/dashboard/model/DashBoardDAOImpl.java, rence/src/main/java/test/com/rence/dashboard/service/DashBoardService.java, rence/src/main/resources/jdbc/sqlMapper_backoffice.xml, rence/src/main/resources/jdbc/sqlMapper_dashboard.xml, rence/src/main/resources/jdbc/sqlMapper_master.xml
=> [feat] BackOffice tag null 처리

rence/src/main/webapp/WEB-INF/tiles_reserve.xml, rence/src/main/webapp/WEB-INF/views/backoffice/landing/insert.jsp, rence/src/main/webapp/WEB-INF/views/office/reserve/payment_page.jsp, rence/src/main/webapp/resources/CSS/backoffice/host-insert.css, rence/src/main/webapp/resources/JS/backoffice/host_insert.js
- 사업자 번호 정규표현식으로 형식 체크
- 업체 번호 정규표현식으로 형식 체크
=> [feat] 호스트 신청 조건 추가

rence/src/main/java/test/com/rence/backoffice/BackOfficeController.java, rence/src/main/java/test/com/rence/master/MasterController.java, rence/src/main/resources/jdbc/sqlMapper_dashboard.xml, rence/src/main/resources/jdbc/sqlMapper_master.xml
=> [feat] BackOffice, Master 로그아웃 버그 수정

rence/src/main/java/test/com/rence/dashboard/DashBoardController.java, rence/src/main/java/test/com/rence/dashboard/model/DashBoardDAOImpl.java, rence/src/main/java/test/com/rence/master/MasterDAOImpl.java, rence/src/main/resources/jdbc/sqlMapper_dashboard.xml
=> [feat] 정산 완료 시, 마일리지 상태 변경

rence/src/main/java/test/com/rence/backoffice/BackOfficeDAOImpl.java, rence/src/main/java/test/com/rence/dashboard/DashBoardController.java, rence/src/main/java/test/com/rence/master/MasterController.java, rence/src/main/java/test/com/rence/sendemail/MasterSendEmail.java
=> [feat] BackOffice 비밀번호 설정 암호화,복호화 base64로 변경

rence/src/main/java/test/com/rence/backoffice/BackOfficeController.java, rence/src/main/java/test/com/rence/master/MasterController.java, rence/src/main/resources/jdbc/sqlMapper_dashboard.xml
=> [refactor] 로그아웃 시, 세션 처리 수정

rence/src/main/resources/jdbc/sqlMapper_dashboard.xml
=> [refactor] dashboard Mapper 수정

rence/src/main/java/test/com/rence/dashboard/DashBoardController.java, rence/src/main/java/test/com/rence/dashboard/model/DashBoardDAO.java, rence/src/main/java/test/com/rence/dashboard/model/DashBoardDAOImpl.java, rence/src/main/java/test/com/rence/dashboard/service/DashBoardService.java, rence/src/main/resources/jdbc/sqlMapper_dashboard.xml
=> [feat] search 예약 상태에 따른 검색

rence/src/main/java/test/com/rence/dashboard/model/DashBoardDAOImpl.java, rence/src/main/resources/jdbc/sqlMapper_dashboard.xml
=> [feat] dashboard 정산 구현

rence/src/main/java/test/com/rence/dashboard/DashBoardController.java, rence/src/main/java/test/com/rence/dashboard/model/DashBoardDAOImpl.java, rence/src/main/resources/jdbc/sqlMapper_dashboard.xml
=> [feat] 공간 추가/ 수정 servlet 분리

rence/src/main/java/test/com/rence/dashboard/DashBoardController.java
=> [refactor] 공간 타입 한글-영어 수정

rence/src/main/java/test/com/rence/dashboard/model/DashBoardDAOImpl.java, rence/src/main/java/test/com/rence/dashboard/model/ReserveVO_date.java, rence/src/main/resources/jdbc/sqlMapper_dashboard.xml
=> [refactor] room update mapper  수정

rence/src/main/java/test/com/rence/dashboard/DashBoardController.java, rence/src/main/java/test/com/rence/dashboard/model/DashBoardDAOImpl.java, rence/src/main/resources/jdbc/sqlMapper_dashboard.xml
=> [feat]  공간 삭제 시, 조건 추가

rence/src/main/java/test/com/rence/dashboard/DashBoardController.java
backoffice_type -> room_type 수정
=> [error] room_type 수정

rence/src/main/java/test/com/rence/backoffice/BackOfficeController.java, rence/src/main/resources/jdbc/sqlMapper_dashboard.xml
=> [refactor] BackOffice_type 수정

rence/src/main/java/test/com/rence/backoffice/BackOfficeController.java, rence/src/main/resources/jdbc/sqlMapper_dashboard.xml
=> [error] room_type value 변경

rence/src/main/java/test/com/rence/dashboard/DashBoardController.java, rence/src/main/java/test/com/rence/dashboard/model/DashBoardDAO.java, rence/src/main/java/test/com/rence/dashboard/model/DashBoardDAOImpl.java, rence/src/main/java/test/com/rence/dashboard/service/DashBoardService.java, rence/src/main/resources/jdbc/sqlMapper_dashboard.xml
=> [refactor] comments 쿼리문 수정

rence/src/main/java/test/com/rence/dashboard/DashBoardController.java, rence/src/main/java/test/com/rence/dashboard/model/CommentListVO.java, rence/src/main/java/test/com/rence/dashboard/model/DashBoardDAO.java, rence/src/main/java/test/com/rence/dashboard/model/DashBoardDAOImpl.java, rence/src/main/java/test/com/rence/dashboard/service/DashBoardService.java, rence/src/main/resources/jdbc/sqlMapper_dashboard.xml
=> [refactor] comments 수정

rence/src/main/java/test/com/rence/dashboard/model/CommentListVO.java, rence/src/main/java/test/com/rence/dashboard/model/DashBoardDAOImpl.java
=> [error] comments list 재수정

rence/src/main/java/test/com/rence/dashboard/model/CommentListVO.java, rence/src/main/java/test/com/rence/dashboard/model/DashBoardDAOImpl.java, rence/src/main/resources/jdbc/sqlMapper_dashboard.xml
=> [refactor] comments room_no 추가

rence/src/main/java/test/com/rence/dashboard/model/DashBoardDAOImpl.java
=> [error] comments 답글 없을 때 에러 수정

rence/src/main/java/test/com/rence/dashboard/model/DashBoardDAOImpl.java, rence/src/main/java/test/com/rence/dashboard/model/RoomVO.java
=> [error] RoomVO "" 처리

rence/src/main/resources/jdbc/sqlMapper_dashboard.xml
=> [error] content_no->comment_no

rence/src/main/java/test/com/rence/dashboard/model/CommentVO.java
=> [error] room_no 오타 수정

rence/src/main/resources/jdbc/sqlMapper_dashboard.xml
=> [error] Mapper 오류 수정

rence/src/main/resources/jdbc/sqlMapper_dashboard.xml
=> [error] room_name 출력

rence/src/main/java/test/com/rence/dashboard/model/DashBoardDAOImpl.java, rence/src/main/resources/jdbc/sqlMapper_dashboard.xml
=> [refactor] comments 구현 중

rence/src/main/java/test/com/rence/backoffice/BackOfficeController.java, rence/src/main/java/test/com/rence/dashboard/DashBoardController.java, rence/src/main/java/test/com/rence/dashboard/model/DashBoardDAOImpl.java, rence/src/main/resources/jdbc/sqlMapper_dashboard.xml
comments 목록 수정, 정산 완료 시, 마일리지 상태 변경
=> [feat] comments 목록 수정, 정산 완료 시, 마일리지 상태 변경

rence/src/main/resources/jdbc/sqlMapper_backoffice.xml
=> [error] email 중복 체크 시, 탈퇴 회원 제외

rence/src/main/resources/jdbc/sqlMapper_backoffice.xml
=> [error] pw 찾기 수정 중

rence/src/main/resources/jdbc/sqlMapper_backoffice.xml
=> [refactor] pw 수정중

rence/src/main/java/test/com/rence/dashboard/DashBoardController.java, rence/src/main/java/test/com/rence/dashboard/model/DashBoardDAOImpl.java, rence/src/main/java/test/com/rence/dashboard/model/SalesSettlementVO.java, rence/src/main/resources/jdbc/sqlMapper_dashboard.xml
=> [error] 정산 리스트 출력

rence/src/main/java/test/com/rence/backoffice/BackOfficeController.java, rence/src/main/java/test/com/rence/backoffice/BackOfficeDAO.java, rence/src/main/java/test/com/rence/backoffice/BackOfficeDAOImpl.java, rence/src/main/java/test/com/rence/backoffice/BackOfficeService.java
=> [refactor] pw 찾기 수정 완료

rence/src/main/java/test/com/rence/dashboard/model/DashBoardDAOImpl.java, rence/src/main/webapp/WEB-INF/views/backoffice/dash_board/setting.jsp
=> [feat] 환경설정 jsp

rence/src/main/java/test/com/rence/dashboard/DashBoardController.java, rence/src/main/java/test/com/rence/dashboard/model/DashBoardDAOImpl.java, rence/src/main/resources/jdbc/sqlMapper_dashboard.xml
=> [refactor] 일일 정상 출력

rence/src/main/java/test/com/rence/dashboard/model/DashBoardDAOImpl.java, rence/src/main/resources/jdbc/sqlMapper_dashboard.xml
=> [refactor] 주간, 월간 정산 출력

rence/src/main/resources/jdbc/sqlMapper_dashboard.xml
=> [refactor] 정산 상태 변경 쿼리 수정

rence/pom.xml, rence/src/main/java/test/com/rence/backoffice/BackOfficeController.java, rence/src/main/java/test/com/rence/backoffice/BackOfficeDAO.java, rence/src/main/java/test/com/rence/backoffice/BackOfficeDAOImpl.java, rence/src/main/java/test/com/rence/backoffice/BackOfficeFAO.java, rence/src/main/java/test/com/rence/backoffice/BackOfficeFAOImpl.java, rence/src/main/java/test/com/rence/backoffice/BackOfficeFileService.java, rence/src/main/java/test/com/rence/backoffice/BackOfficeService.java, rence/src/main/java/test/com/rence/dashboard/DashBoardController.java, rence/src/main/java/test/com/rence/dashboard/model/CommentSummaryVO.java, rence/src/main/java/test/com/rence/dashboard/model/ReserveSummaryVO.java, rence/src/main/java/test/com/rence/dashboard/model/ReviewVO.java, rence/src/main/java/test/com/rence/dashboard/model/RoomSummaryVO.java, rence/src/main/java/test/com/rence/dashboard/model/SalesSettlementVO.java, rence/src/main/java/test/com/rence/master/MasterController.java, rence/src/main/java/test/com/rence/master/MasterDAOImpl.java, rence/src/main/java/test/com/rence/sendemail/AES256Util.java, rence/src/main/java/test/com/rence/sendemail/AuthVO.java, rence/src/main/java/test/com/rence/sendemail/EmailVO.java, rence/src/main/resources/jdbc/sqlMapper_backoffice.xml, rence/src/main/resources/jdbc/sqlMapper_dashboard.xml, rence/src/main/resources/jdbc/sqlMapper_master.xml, rence/src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
=> [refacjtor] 코드 작성자 추가 - 최진실
